config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "members#new"
  resources :friendships
  resources :sessions

  get "/members/:id", to: "members#show"
  post "/create_member", to: "members#new"
  post "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, :class_name => "Member"
end

app/models/member.rb
require 'bitly'

class Member < ApplicationRecord

  # Define self-referential relationships for friending functionalities
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :member

  # Store member website headings
  has_many :site_contents

  attr_accessible :first_name, :last_name, :username, :password, :url, :short_url
  attr_accessor :password
  before_save :prepare_username, :prepare_password, :prepare_short_url

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password

  def self.authenticate(first_name, last_name, url, pass)
    username = "#{first_name}_#{last_name}_#{url}"
    member = find_by_username(username)
    return member if member && member.matching_password?(pass)
  end
  
  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end
  
  private

  BITLY_ACCESS_TOKEN = '054d6f655c159676369320125e6c8cb4293082f4'

  # Username would be the combination of first/last name of the member and the website URL
  def prepare_username
    self.username = "#{first_name}_#{last_name}_#{url}"
  end
  
  # Password would be hashed before storage
  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hash = encrypt_password(password)
    end
  end

  def prepare_short_url
    self.short_url = generate_short_url(url)
  end
  
  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end

  # Using Bitly gem for generating shorten URL with temporarly access token retrieved from Bitly official website
  def generate_short_url(url)
    bitly_client = Bitly::API::Client.new(token: BITLY_ACCESS_TOKEN)
    bitlink = bitly_client.shorten(long_url: url)
    bitlink.link
  end
end

app/models/site_content.rb
class SiteContent < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  helper :all
  protect_from_forgery
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_member.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added as friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end
  
  def destroy
    @friendship = current_member.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed from friend list."
    redirect_to current_member
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def show
    @member = current_member
  end
  
  def new
    @member = Member.new
  end
  
  def create
    @member = Member.new(params[:member])
    if @member.save
      @member.site_contents.create!(url: @member.url)  # Store member website headings on member creation
      session[:member_id] = @member.id
      flash[:notice] = "Thank you for creating new member! You are now logged in as the member just created."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    member = Member.authenticate(params[:first_name], params[:last_name], params[:url], params[:password])
    if member
      session[:member_id] = member.id
      flash[:notice] = "Logged in successfully."
      redirect_to root_url
    else
      flash.now[:error] = "Invalid name, URL or password."
      render :action => 'new'
    end
  end
  
  def destroy
    session[:member_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_url
  end
end

app/controllers/site_contents_controller.rb
require 'nokogiri'
require 'open-uri'

class SiteContentsController < ApplicationController
  def create
    # Scrap webpage content in HTML using Nokogiri based on valid URL of the associated member
    if params[:url]
      html_content = URI.open(params[:url])
      if html_content
        doc = Nokogiri::HTML(html_content)

        # Get all h1-h3 headings in the specific page and store as SiteContent active records, "h1/h2/h3" as type and the actual heading value as context value
        doc.css('h1', 'h2', 'h3').each do |element|
          @site_content = SiteContent.new(:type => element.name, :context => element.text)
          @site_content.save
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_contents_helper.rb
module SiteContentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndopenSocialNetworking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<% title "Member List" %>

<div id="members">
<% for member in @members %>
  <div class="member">
    <p>
      <strong><%=h member.first_name %> <%=h member.last_name%></strong>
      <%= link_to "Add Friend", friendships_path(:friend_id => member), :method => :post %>
      <div class="clear"></div>
    </p>
  </div>
<% end %>
</div>

app/views/members/new.html.erb
<% title "Create new member" %>

<p>Member already created? <%= link_to "Log in", login_path %>.</p>

<% form_for @member do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name, "First Name" %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :url, "Website Address" %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Create Member" %></p>
<% end %>

app/views/members/show.html.erb
<% title "Member Profile" %>

<p>Username: <%=h @member.first_name %> <%=h @member.last_name %> </p>


<h2>Friends</h2>
<ul>
  <% for friendship in @member.friendships %>
    <li>
      <%=h friendship.friend.first_name %> <%=h friendship.friend.last_name %>: <%=h friendship.friend.short_url %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", members_path %></p>

<h2>Friended by Members</h2>
<ul>
  <% for member in @member.inverse_friends %>
    <li><%=h member.first_name %> <%=h member.last_name %>: <%=h member.short_url %></li>
  <% end %>
</ul>